spring:
  cloud:
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: ${rabbitmq.host}
    port: ${rabbitmq.port}
    username: ${rabbitmq.username}
    password: ${rabbitmq.password}
  redis:
    host: ${redis.host}
    port: ${redis.port}
    lettuce:
      pool:
        max-active: 300
    password: ${redis.password}
  datasource:
    driver-class-name: ${database.driver-class-name}
    url: jdbc:postgresql://${database.host}:${database.port}/sc_product?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: ${database.username}
    password: ${database.password}
  zipkin:
    enabled: true
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0
  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-request-size: "2MB"
      max-file-size: "2MB"
  jackson:
    time-zone: GMT+8
#  resources:
#    add-mappings: false

logging:
  level:
    java:
      sql:
        PreparedStatement: debug
    com:
      springboot: debug
  path: logs/
  file:
    max-size: 1GB

management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  configuration:
    map-underscore-to-camel-case: true

mybatis-plus:
  global-config:
    db-config:
      id-type: 0 # 0为AUTO
      logic-delete-value: "Y" # 逻辑已删除值(默认为 Y)
      logic-not-delete-value: "N" # 逻辑未删除值(默认为 N)