version: '3'
services:
  #授权服务
  authorization-server:
    image: 10.0.0.102:java/authorization-server:latest
    container_name: sc-authorization-server
    restart: always
    networks:
      - sc-net
    ports:
      - 8000:8000
    env_file: .env
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - authentication-server

  #认证服务
  authentication-server:
    image: 10.0.0.102:java/authentication-server:latest
    container_name: sc-authentication-server
    restart: always
    networks:
      - sc-net
    ports:
      - 8001:8001
    env_file: .env
    environment:
      TZ: Asia/Shanghai
networks:
  sc-net:
    external: false