version: '3'
services:
  #监控管理台服务
  monitor-admin:
    image: 10.0.0.102/java/admin:latest
    container_name: sc-monitor-admin
    restart: always
    networks:
      - sc-net
    ports:
      - 8022:8022
    env_file: .env
    environment:
      TZ: Asia/Shanghai

  sentinel-dashboard:
    image: cike/sentinel-dashboard-docker:latest
    container_name: sc-sentinel-dashboard
    restart: always
    networks:
      - sc-net
    ports:
      - 18021:8021
    env_file: .env
networks:
  sc-net:
    external: false