version: '3'
services:
  #Moss管理中心
  moss:
    image: 10.0.0.102/java/moss-web:latest
    container_name: moss
    restart: always
    networks:
      - sc-net
    ports:
      - 8086:8086
    env_file: .env
    environment:
      TZ: Asia/Shanghai
networks:
  sc-net:
    external: false