version: '3'
services:
  # web聚合服务
  k12-java-webmerge:
    image: 10.0.0.102/java/k12-java-webmerge:latest
    container_name: sc-k12-java-webmerge
    restart: always
    networks:
      - sc-net
    ports:
      - 8096:8096
    env_file: .env
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - k12-java-appmerge
  # app聚合服务
  k12-java-appmerge:
    image: 10.0.0.102/java/k12-java-appmerge:latest
    container_name: sc-k12-java-appmerge
    restart: always
    networks:
      - sc-net
    ports:
      - 8097:8097
    env_file: .env
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - k12-java-material
  # 介质服务
  k12-java-material:
    image: 10.0.0.102/java/k12-java-material:latest
    container_name: sc-k12-java-material
    restart: always
    networks:
      - sc-net
    ports:
      - 9002:9002
    env_file: .env
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - k12-java-coreserver
  # 访客服务
  k12-java-visitor:
    image: 10.0.0.102/java/k12-java-visitor:latest
    container_name: sc-k12-java-visitor
    restart: always
    networks:
      - sc-net
    ports:
      - 8094:8094
    env_file: .env
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - k12-java-coreserver
  # 进出服务
  k12-java-leave:
    image: 10.0.0.102/java/k12-java-leave:latest
    container_name: sc-k12-java-leave
    restart: always
    networks:
      - sc-net
    ports:
      - 8021:8021
    env_file: .env
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - k12-java-coreserver
  # 核心业务服务
  k12-java-coreserver:
    image: 10.0.0.102/java/k12-java-coreserver:latest
    container_name: sc-k12-java-coreserver
    restart: always
    networks:
      - sc-net
    ports:
      - 8061:8061
    env_file: .env
    environment:
      TZ: Asia/Shanghai

networks:
  sc-net:
    external: false