spring:
  rabbitmq:
    host: ${rabbitmq.host}
    port: ${rabbitmq.port}
    username: ${rabbitmq.username}
    password: ${rabbitmq.password}
  redis:
    host: ${redis.host}
    port: ${redis.port}
    password: ${redis.password}
  datasource:
    driver-class-name: ${database.driver-class-name}
    url: jdbc:postgresql://${database.host}:${database.port}/sc_product?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: ${database.username}
    password: ${database.password}
  zipkin:
    enabled: true
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0
  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-request-size: "2MB"
      max-file-size: "2MB"
  jackson:
    time-zone: GMT+8
  jpa:
    show-sql: true
    generate-ddl: true

logging:
  level:
    org.springframework.web: debug
    java.sql.PreparedStatement: debug
  path: logs/
  file:
    max-size: 1GB

management:
  endpoints:
    web:
      exposure:
        include: '*'
